# Generated by Django 3.2.7 on 2021-10-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('recipient', models.CharField(max_length=100)),
                ('parcels_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('treck', models.CharField(default=False, max_length=50, unique=True)),
                ('category', models.CharField(default=False, max_length=100)),
                ('status', models.CharField(choices=[('unregistered_order', 'незарегистрированный заказ'), ('during', 'в процессе'), ('sorting', 'сортировка'), ('processed_1', 'обработан1'), ('processed_2', 'обработан2'), ('processed_3', 'обработан3'), ('In_stock_in_KG1', 'на складе в Kg1'), ('In_stock_in_KG2', 'на складе в Kg2'), ('In_stock_in_KG3', 'на складе в Kg3')], default='unregistered_order', max_length=50)),
                ('web_site', models.URLField(default=False)),
                ('comment', models.TextField(max_length=324, null=True)),
                ('order', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
