# Generated by Django 3.2.7 on 2021-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_in',
            field=models.ImageField(default=1, upload_to='scan_in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passport_out',
            field=models.ImageField(default=1, upload_to='scan_out'),
            preserve_default=False,
        ),
    ]
