# Generated by Django 3.2.7 on 2021-10-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_out',
        ),
    ]
