# Generated by Django 3.2.7 on 2021-10-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
